### ISSUE TITLE
Installing on Mac ARM

### ISSUE THREAD

**Issue by maurosilber** [royerlab/ultrack#193]
Hi!

I'm trying to install `ultrack` on Mac ARM64, but it is failing to resolve the dependencies.

As `ultrack` has many dependencies, and there could be issues with other packages I had, I tried installing on an isolated environment, but it still failed to resolve. This is the corresponding `pixi.toml`:

```toml
platforms = ["osx-arm64"]

[dependencies]
python = "<3.12"
higra = "*"  # only available from conda-forge on osx-arm64

[pypi-dependencies]
ultrack = "*"
```

I was wondering if anyone was able to install it on `osx-arm64`.

## Minimal dependencies

If I cloned the git repo and tried to remove some dependencies, what would be some minimal dependencies that would allow to perform tracking on segmentation masks?

Would I need to install: 
- GUI-related things like `napari`, `magicgui`, `qtpy`?
- server-related dependencies such as `uvicorn`, `httpx`, `fastapi`?

Thanks!

## Dependency resolution error

It's not that enlightening (to me) but, just in case, here is the dependency resolution error:
```
├─▶ failed to resolve pypi dependencies
  ╰─▶ Because numba==0.56.4 depends on numpy>=1.18,<1.24 and numpy==2.2.2, we can conclude that numba==0.56.4 cannot be used.
      And because only the following versions of numba are available:
          numba<=0.56.4
          numba>0.57.0
      we can conclude that numba>=0.56.4,<0.57.0 cannot be used.
      And because ultrack==0.1.0 depends on numba>=0.56.4,<0.57.0 and only the following versions of ultrack are available:
          ultrack==0.1.0
          ultrack==0.2.0
          ultrack==0.3.0
          ultrack==0.3.1
          ultrack==0.5.0
          ultrack==0.6.0
          ultrack==0.6.1
          ultrack==0.6.3
      we can conclude that ultrack<0.2.0 cannot be used. (1)
      
      Because numba>=0.57.0,<=0.57.1 depends on numpy>=1.21,<1.25 and numpy==2.2.2, we can conclude that numba>=0.57.0,<=0.57.1
      cannot be used.
      And because only the following versions of numba are available:
          numba<=0.57.0
          numba==0.57.1
          numba>0.58.0
      and ultrack>=0.2.0,<=0.5.0 depends on numba>=0.57.0,<0.58.0, we can conclude that ultrack>=0.2.0,<=0.5.0 cannot be used.
      And because we know from (1) that ultrack<0.2.0 cannot be used, we can conclude that ultrack<0.6.0 cannot be used. (2)
      
      Because only mip<1.16rc0 is available and ultrack>=0.6.0 depends on mip>=1.16rc0, we can conclude that ultrack>=0.6.0 cannot
      be used.
      And because we know from (2) that ultrack<0.6.0 cannot be used, we can conclude that all versions of ultrack cannot be used.
      And because you require ultrack, we can conclude that your requirements are unsatisfiable.
```

**Comment by JoOkuma** [comment]
Hi @maurosilber,

I'm also using `pixi` in some of my projects that depends on `ultrack`.

`mip` is a problematic dependency. What did for me was adding this to my `pixi` configuration (I'm using pyproject.toml in this case, but it should be the same for you):

```toml
# pixi config
[tool.pixi.project]
...
preview = ["pixi-build"]

...
[dependencies]
higra = "*"  # as you already did only

...
[tool.pixi.pypi-dependencies]
mip = ">=1.16rc0"
ultrack = "*"
```

If this doesn't work let me know

**Comment by maurosilber** [comment]
I tried that, but it didn't work. It still complains about numba, numpy and ultrack versions.

**Comment by maurosilber** [comment]
It works with:
```toml
[dependencies]
python = "<3.12"
higra = "*"
numba = "*"
psycopg2-binary = ">=2.9.6"

[pypi-dependencies]
ultrack = "*"
mip = ">=1.16rc0"
```

`higra` depends on `numpy` and, since the `pypi-dependencies` solve happens after pinning the conda dependencies, it was installing a version of `numpy` that was not compatible with `numba`.
